### ISSUE TITLE
ISSUE 01

### ISSUE THREAD

**Issue by kimduuukbae** [19-2-ServerProject1/SeverProject#1]
안녕하세요. 이 리포지토리에 제가 추가가 되어 있어 Issue 추가합니다.
제가 왜 추가가 된진 모르겠으나 Github Arctic Archive 때문인것 같습니다.
저는 현재 겜공 4학년인 14학번 오한빛찬입니다.

OPENGL 이랑 서버소스 보니 19-2에 3학년이셨던 것 같은데, 혹여나 소스 유출이 있을 뿐더러
Commit 에 제 계정이 올라가 있습니다.. 처음 보는 리포지토리인데 확인 부탁드립니다.

**Comment by YouMustStudy** [comment]
안녕하세요.
확인이 늦어서 죄송합니다. 오랜만에 깃을 켜봤더니 이슈를 남겨주셨네요.
문의주신 계정으로 올라간 커밋들은 모두 수정 완료했습니다.

감사합니다.
